base: ghcr.io/vanilla-os/pico:main
name: Vanilla Dev
singlelayer: false
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

- name: packages-modules
  type: includes
  includes:
    - modules/00-go.yml
    - modules/10-python.yml
    - modules/20-build-tools.yml
    - modules/30-gtk.yml
    - modules/40-rust.yml

- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
  - rm -rf /var/cache/*
  - rm -rf /tmp/*
  - rm -rf /var/tmp/*
  - rm -rf /sources
  - mkdir -p /var/cache/apt/archives/partial
