base: ghcr.io/vanilla-os/pico:main
name: Vanilla Dev
singlelayer: false
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

modules:
- name: packages-modules
  type: includes
  includes:
    - modules/00-basics
    - modules/05-go
    - modules/10-python
    - modules/20-build-tools
    - modules/30-gtk
    - modules/40-rust

- name: host-spawn
  type: shell
  source:
   type: tar
   url: >-
    https://github.com/1player/host-spawn/releases/download/1.5.0/host-spawn-x86_64
  commands:
    - mv host-spawn-x86_64 /usr/bin/host-spawn
    - chmod +x /usr/bin/host-spawn

- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
  - rm -rf /var/cache/*
  - rm -rf /tmp/*
  - rm -rf /var/tmp/*
  - rm -rf /sources
  - mkdir -p /var/cache/apt/archives/partial
