name: Vanilla Dev
id: dev
stages:
- id: build
  base: ghcr.io/vanilla-os/pico:main
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: packages-modules
    type: includes
    includes:
      - modules/00-basics.yml
      - modules/01-vanilla-base-files.yml
      - modules/05-go.yml
      - modules/10-python.yml
      - modules/20-build-tools.yml
      - modules/30-gtk.yml
      - modules/40-rust.yml
      - modules/100-apx-gui-deps.yml
      - modules/101-abroot-deps.yml
      - modules/200-vib.yml

  - name: host-spawn
    type: shell
    source:
      type: file
      url: https://github.com/1player/host-spawn/releases/download/v1.6.0/host-spawn-x86_64
      checksum: 75159f0d3924a0bd6d230c6414d19ad44609b5a16671db6624681c910f9bb4ff
    commands:
      - cp /sources/host-spawn/host-spawn /usr/bin/host-spawn
      - chmod +x /usr/bin/host-spawn

  - name: cleanup
    type: shell
    commands:
      - apt autoremove -y
      - apt clean
      - rm -rf /var/cache/*
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
      - mkdir -p /var/cache/apt/archives/partial

  - name: add-manpath-config
    type: shell
    commands: 
      - mv /etc/man-path.config /etc/manpath.config
